name: DevSecOps Pipeline

on:
  push:
  pull_request:

jobs:
  security-validation:

    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verificar Secret
        run: |
          if [ -n "$DB_PASSWORD" ]; then
            echo "Secret cargado correctamente"
          else
            echo "Secret no encontrado"
            exit 1
          fi

      - name: Pipeline finalizado
        run: echo "Validaciones completadas"
